# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      next-and-react:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "eslint-config-next"
          - "@next/*"
      supabase:
        patterns:
          - "@supabase/*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
